# Generated by Django 4.2.10 on 2024-02-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('couleur', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
