# Generated by Django 5.0.3 on 2024-03-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_apiobject_delete_fruit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiobject',
            old_name='name',
            new_name='roman_name',
        ),
    ]
